### ISSUE TITLE
UTF-8 for database

### ISSUE THREAD

**Issue by Janhouse** [deStrO/eBot-CSGO#100]
Seems like by default eBot uses latin1 encoding and doesn't support utf-8 encoding.

Could you please make the setup script create database, tables and fields using utf8_general_ci encoding to fix this?

**Comment by deStrO** [comment]
The database script is provided by Symfony and it seems to be configured with UTF8 by default.

**Comment by Janhouse** [comment]
Indeed, my database had default config. It would be good though if symfony forced UTF-8 in this case.
Closing the issue.
