### ISSUE TITLE
Demo button away

### ISSUE THREAD

**Issue by Famous030** [deStrO/eBot-CSGO#107]
Hey,

i running the privately ebot.

demo/download is true (enabled)

But it's away.
(Screenshot):
https://cloud.githubusercontent.com/assets/5301047/16306816/473807f8-395f-11e6-8c73-615e0b84c49c.png

But no "demos" :( 

The demos all correctly in - /home/ebot/ebot-csgo/demos

maybe some help plz

i install Ebot with that tutorial: 
http://forum.esport-tools.net/d/2-how-to-install-ebot-on-debian-ubuntu-for-beginners

and on debian 8.x

**Comment by deStrO** [comment]
Did you cleared the cache?
Check the path in the config file, config/app_user.yml

2016-09-07 10:55 GMT+02:00 Famous030 <notifications@github.com>:

**Comment by Famous030** [comment]
cache cleared and 

 demo_path: /home/ebot/ebot-csgo/demos

  # true or false, whether demos will be downloaded by the ebot server
  # the demos can be downloaded at the matchpage, if it's true

  demo_download: true

  ebot_ip: 37.187.125.89
  ebot_port: 12360

  # lan or net, it's to display the server IP or the GO TV IP
  # net mode display only started match on home page
  mode: net

**Comment by deStrO** [comment]
This is strange, is the directory readable from the webserver?

2016-09-07 11:12 GMT+02:00 Famous030 <notifications@github.com>:

**Comment by Famous030** [comment]
how i can check it ? 
im not to advanced onley work with tutorials

**Comment by Famous030** [comment]
the folder got 755  premissons

**Comment by Famous030** [comment]
push

**Comment by Famous030** [comment]
@deStrO i trying to install your Ebot on Debian 7 up to Debian 8 and on Ubuntu.

Every time with this Tutorial : http://forum.esport-tools.net/d/2-how-to-install-ebot-on-debian-ubuntu-for-beginners

Never get the Demo Button ?! 

And with the new Update i edit app_user.xml
and get this point on webpannel:
https://gyazo.com/1d67059abd06e2c81201a029533fd797

but don't work for me:

https://gyazo.com/2b8de195a393765ab9508197867f850b

HTTP 500 Error

I'm going crazy. I do not get the demo button . and the new update would not work well ...

I need urgent help. can someone help me here ?

I have a server in http://www.kimsufi.com/de/

I despair slowly
