### ISSUE TITLE
eBot is ignoring match password

### ISSUE THREAD

**Issue by gabrielfgularte** [deStrO/eBot-CSGO#113]
Whenever I create a match on the admin, I set a password that is being ignored and any player is able to connect to server. Is this the normal behaviour? Can you guys help me?

**Comment by deStrO** [comment]
If there are players on the server, the password can't be changed.
Try it by your hand to set up the password when you are playing :)

**Comment by gabrielfgularte** [comment]
Hi @deStrO, thanks for reply.

But I'm no trying to change the password. I'm trying to create a match with a password, but the password that is placed on the match creation form is being ignored by some reason.

I don't know if I'm doing right, but when I place some password on match creation form (see the field "password" on the attachment), should this not make the match private and protected by that password?


![captura de tela 2016-12-14 as 18 25 12](https://cloud.githubusercontent.com/assets/1307137/21199550/239bdf18-c22b-11e6-82af-2ea8091c4032.png)

**Comment by deStrO** [comment]
What I'm saying is: when the CSGO server have connected players on the server, nobody can change the password. And it's probably what you are having as issue

**Comment by KoSoVaR** [comment]
If you have a config file setting a password then that could be your problem.  Also the server password must be set, and it usually is on start or on map change.  

Config files need to be really checked, especially if you have other mods/plugins installed and trying to use eBot.

**Comment by gabrielfgularte** [comment]
Alright, thanks!

So you're saying that if I have no players on the server and create a match filling the password form field, it will work?

@KoSoVaR I see. I'll review my config file (that is copied from a ESL config) too check if there's some password on it.

Thank you!

**Comment by KoSoVaR** [comment]
@gabrielfgularte ESL config does not set password.  You're using es5on5.cfg ?  What about the regular server config?  Are you using LGSM to start the server?  So you have an instance-name.cfg file - is there a password in there you maybe set?

**Comment by gabrielfgularte** [comment]
@KoSoVaR I've disconnected all players from server, deleted the ESL config and created a new match with no config file (just the installation default ones). Players still can connect without password. =/

But let me check in the .cfg file if there's any password config. Thanks!

**Comment by KoSoVaR** [comment]
@gabrielfgularte Right, but have you changed the map?  Just changing the password will not take in to effect - a trigger, i.e. map change, has to occur.

**Comment by gabrielfgularte** [comment]
@KoSoVaR There's a password on the .cfg file. Should I have to repeat it when creating the match?

I'm playing in a single map. I've printed the match that I'm trying to create. Check the attachment. Thanks!

![captura de tela 2016-12-14 as 18 49 56](https://cloud.githubusercontent.com/assets/1307137/21200389/2fabbe60-c22e-11e6-9df9-c3521ec32f53.png)

**Comment by KoSoVaR** [comment]
It's been quite some time since I've used eBot but if I remember correctly, once you create a match and then start it, that triggers the whole map reloading and the config loading.  You do not want to have a server password (to be clear, different from the rcon password) in the config files.  This is what eBot will set.  At least, I believe this is the case..

I would go to matches in progress, stop, reload the map, or whatever the GUI functionality allows you to do.  Is this how you are forcing the map to change?

**Comment by gabrielfgularte** [comment]
@KoSoVaR yes! This is how I'm doing. I'm confused, could you help me to understand these configs?

The server config is one that is located at the .cfg file, right? What it does and what it blocks?

The rcon password is the one placed at the match creation form on the eBot admin? What it does and what it blocks?

Thanks!

**Comment by KoSoVaR** [comment]
@gabrielfgularte sorry I wish I could be some more help here.  Like I said, it's been quite some time.

I *believe* you should only be setting the rcon password.  This is the root password of your CSGO server - how it's controlled.  This should not be given to anyone publicly.  It is yours and eBots as to control the CSGO servers.

sv_password should not be set, again, *I BELIEVE* in any of your configs.  When you create a match using eBot, it should load the map and while doing so set the password (sv_password).  That password is the password to connect to the server.

**Comment by gabrielfgularte** [comment]
I see. @KoSoVaR and @deStrO, please, let me explain what I'm trying to accomplish.

I'm starting a new web based platform for CS:GO with casual games and tournaments. Just like gamersclub.com.br and www.faceit.com. I have a good investor and have other 3 people working on back-end API, design and front-end for the platform.

I'm trying to use AWS with Docker containers to host both gameserver and eBot. Everything works just fine and we are very close to launch the platform.

There are missing only two parts:
- setup eBot accordingly to our desires - and this includes block the match by password;
- record the demo files;

We have our eBot working here: http://52.67.116.72/ and we're making some manually tests to check if everything is ok. After all features are checked, we'll going to start the gameserver and matches via our API. But we're facing these two problems above in our manual tests.

I'm doing something wrong?
Why the password is ignored when I create a match on eBot admin's match creation form?
Why eBot isn't recording the demo files on the demo/ folder?

Can you guys help me a little bit with these additional informations?
