### ISSUE TITLE
cSay !help !rules

### ISSUE THREAD

**Issue by EazYKevin** [deStrO/eBot-CSGO#116]
hello

i just installed eSay/eBot on my server
and cant get these two commands to work
!help !rules

any help ?

best regrads 
EazYKevin

**Comment by Nols1000** [comment]
Hello @EazYKevin,
do you run an instance of eBot or did you just install the cSay SourceMod plugin. It just works if you're running an instance of eBot. 

If you're running an instance of eBot please post your log here. Please also provide some Information about your system. (Operating System, PHP version, Node.js version).
