### ISSUE TITLE
php 7.2

### ISSUE THREAD

**Issue by pmaster555** [deStrO/eBot-CSGO#118]
Fatal error: Declaration of UDPSocket::connect($ipAddress, $portNumber, $timeout) must be compatible with Socket::connect(string $host, int $port): bool in /home/ebot/vendor/koraktor/steam-condenser/lib/UDPSocket.php on line 56

**Comment by vince52** [comment]
Hello, ebot is not available with php7.
eBot 4.0 will be with php7.

The only version you can use is php5.

**Comment by marcobuettner** [comment]
any news?

**Comment by Bouman** [comment]
any news?
