### ISSUE TITLE
extra messages ingame

### ISSUE THREAD

**Issue by martinrundstrom** [deStrO/eBot-CSGO#122]
Is there a cfg or txt file for eBot or is it web-based?

I want to add extra messages like the one ebots sends out.
And such. Best Regards

**Comment by deStrO** [comment]
You can use the season to add custom messages :)
You have to restart your daemon after each changes.

2017-03-21 16:53 GMT+01:00 martinrundstrom <notifications@github.com>:

**Comment by martinrundstrom** [comment]
Hello deStrO,

I'm lost, use the season to add? .. daemon?:D
Any online guide that you've published somewhere?

Thanks for the quick response and also for the fast response earlier this year, on twitter.

**Comment by martinrundstrom** [comment]
Anyone who can explain this or send me a guide of some sort?

best regards

**Comment by wAsnk** [comment]
@martinrundstrom  Are you using the public eBot? http://public.ebot.wedeho.be/
Or a private one?

**Comment by martinrundstrom** [comment]
@wAsnk I'm using the public one. Installed Csay via my server provider.

**Comment by wAsnk** [comment]
@martinrundstrom You can't add extra messages with the public one. You need to run your own eBot service.

**Comment by martinrundstrom** [comment]
@wAsnk ah ok, is there any guide for that? I have my own php server and such.

**Comment by wAsnk** [comment]
@martinrundstrom For Ubuntu/Linux: http://forum.esport-tools.net/d/2-how-to-install-ebot-on-debian-ubuntu-for-beginners

Also for Docker: http://forum.esport-tools.net/d/80-ebot-docker-3

**Comment by martinrundstrom** [comment]
@wAsnk Sweet bro. I dont know if I'm able to run applications on my webserver (linux) i think it is.
But I have a shitty media computer, by shitty I mean all the worlds shits put into one pc. Can I install docker on that one you think, is there any special requirements?

**Comment by martinrundstrom** [comment]
That computer was able to run a 1.6 server, if that gives you any guidelines about its performance

**Comment by martinrundstrom** [comment]
@wasnk Im considering renting a vps. All though I dont know what specs I need, for running a csgo server there aswell, do you know?
