### ISSUE TITLE
csay_tv_demo_push not being sent via rcon to server

### ISSUE THREAD

**Issue by Flegma** [deStrO/eBot-CSGO#126]
Hello,
i've installed newest eBot version from the Github and everything is ok, but the demos are not pushed to the server.
On the war server there is no "csay_tv_demo_push" command in the log.
I have double checked the configs for demos download and in ebot-csgo config.ini i have
DEMO_DOWNLOAD = true;
and in ebot-web config/app_user.yml i have set correct path and demo download:
demo_path: /home/ebot/ebot-csgo/demos
demo_download: true

Thanks in advance.

**Comment by SeatloN** [comment]
Do you have a windows or Linux game server?

Only Linux support that command what i know.

**Comment by Flegma** [comment]
Linux server.
The issue is fixed with new CSay plugin. The old one didnt send the command to the server.

Thanks anyway.
