### ISSUE TITLE
CLI Has stopped Working / eBot cant connect to Web Panel

### ISSUE THREAD

**Issue by ghost** [deStrO/eBot-CSGO#127]
I tried installing eBot for Windows using  WAMP as an environment, therefore using:

- Windows 10
- Apache 2.4.23
- PHP 5.6.25 (also for CLI)
- MySQL 5.7.14

Everything worked after a few tweaks, however, my Web Panel always has the following status
![image](https://cloud.githubusercontent.com/assets/8009706/26042261/44c1c512-390a-11e7-8a31-79ba234488f7.png)

And after a few seconds, the eBot process, started with:
>  php bootstrap.php

Gives the following output:
![image](https://cloud.githubusercontent.com/assets/8009706/26042296/840a9816-390a-11e7-9c1b-1de876c55da7.png)

Following a crash of the eBot process... Any ideias on how to fix it ?
I appreciate your attention!
Best Regards

**Comment by Cyfer6969** [comment]
Now I have this message on the WebSocket.bat process:
![image](https://cloud.githubusercontent.com/assets/8009706/26043075/08bc6c50-3911-11e7-8481-cdefdcc7f778.png)

**Comment by Cyfer6969** [comment]
I found that this crash happens when I click anywhere the eBot Web Panel.

It has something to do with the WebSocket ... I have tried inspecting the code but I have little to no knowledge of PHP

**Comment by Cyfer6969** [comment]
If I do not open the admin.php page the bot doesnt crash !!!! It certainly has something to do with it

**Comment by heew** [comment]
This still a issue or what? It looks like something is off with your config. I have not used Windows (yuck) for this before, so there could be something there too..

**Comment by AbbyM** [comment]
Hey there,
It's still an issue, watch this : https://github.com/deStrO/eBot-CSGO/pull/117.
I'm now sure that this pull request can help a lot of people..

**Comment by AbbyM** [comment]
You can just edit websocket_server.js like the pull request.
