### ISSUE TITLE
Server crashes on command csay_tv_demo_push

### ISSUE THREAD

**Issue by csplkiller** [deStrO/eBot-CSGO#128]
Server crashes on command csay_tv_demo_push

The server crashes after trying to transfer the demo to the site.

`
PreMinidumpCallback: updating dump comment  
assert_20170521171223_1.dmp[12924]: Uploading dump (out-of-process)  
/tmp/dumps/assert_20170521171223_1.dmp  
assert_20170521171223_1.dmp[12924]: Finished uploading minidump (out-of-process): success = yes  
assert_20170521171223_1.dmp[12924]: response: Discarded=1  
assert_20170521171223_1.dmp[12924]: file ''/tmp/dumps/assert_20170521171223_1.dmp'', upload yes: ''Discarded=1''  
Segmentation fault (core dumped)  
BFD: Предупреждение: /home/cs/srcds380/core усечён: ожидался размер ядра файла >= ‎329240576, найдено: ‎1097728.  
Cannot access memory at address 0xb773a91c  
Cannot access memory at address 0xb773a918  
Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0xbfa314d4:  
debug.cmds:1: Error in sourced command file:  
Cannot access memory at address 0xbfa314d4  
email debug.log to linux@valvesoftware.com  
Вс май 21 17:12:57 MSK 2017: Server restart in 10 seconds  
`

Probably need to update the csay plugin
Can you help me?

**Comment by Kikerechu** [comment]
Just update your CSay to the latest version. 

http://www.esport-tools.net/download/CSay-CSGO.zip
