### ISSUE TITLE
Error In-Game

### ISSUE THREAD

**Issue by SenorME** [deStrO/eBot-CSGO#129]
Hello, 
I just installed today e-Bot, the website is working great, I did start a match with 2 teams, but when I'm trying to use e-Bot commands (!help, !rules, !ready, !notready) nothing works, I have this error:
2017-06-23 19:40:30 - ERROR  [eTools\Rcon\CSGO] Error while doing exec server.cfg You have been banned from this server.

Thanks..

**Comment by SenorME** [comment]
+` RCon password is match

**Comment by Nols1000** [comment]
Have you installed CSay?
Can you provide your CSGO-Server Logs and server.cfg of the Server you connect to? (Note: please mask your server- and rcon-passwords)
