### ISSUE TITLE
[Feature Request] Ability to download Team Logos from Game Servers path

### ISSUE THREAD

**Issue by TandelK** [deStrO/eBot-CSGO#132]
All most all the major of the Online Tournament have to be using Custom Team Logos now but they do require Sourcemod Plugin called Team Logos Manager. I would love to see eBot officially bring Logo Support and make it download from Game Server path to Client . This includes fastdl also. 

You can download required logos from csgo/resource/flash/econ/tournaments/teams/

I have already tried to use this and seems to be working fine for me.

**Comment by heew** [comment]
How have you tried to use it? Do you have any sample code? Or is it just a "plug and play" plugin?

**Comment by TandelK** [comment]
I tried to use it manually and sourcemod version. I havnt done any eBot testing

**Comment by heew** [comment]
To me, it looks to be just a sourcemod plugin that you add and you put desired logos under the resource path and set some cvars.

This means it can already be used with eBot assuming the config you chose to use for the match includes the cvars eg appending the following to the end of the match cfg file should suffice:
teamlogo_autologos 1

Unless I am missing something then I don't think anything else is required. Even though we can set these  cvars from eBot and say you need to have this plugin - I don't think forcing people to use this plugin is a good path, but to me it looks like the option to use it is there now.
