### ISSUE TITLE
"loading" in left side of web page

### ISSUE THREAD

**Issue by Pilik** [deStrO/eBot-CSGO#136]
So, i installed bot in virtual box (ubuntu 14), make bridge and run the bot
ip: 192.168.1.15
I have CS:GO server on 192.168.1.13 (also it's host of virtual box)

In left side of web i see 3 word:
Loading
Loading
Sound On (Turn Off)
But bot is working! He's come to server and start to rule it (+cssay + green and white letters).
But in web if i try to stop them i got nothing. 
Also i can't delete match and can't delete CS:GO server in "manage server" (because hi's in use).

Help me please, how to solve it =( I guess i make some mistakes in configs... 
What i changed:

 config.ini:
MYSQL_IP = "127.0.0.1"
MYSQL_PORT = "3306"
MYSQL_USER = "ebotv3"
MYSQL_PASS = "somepass"
MYSQL_BASE = "ebotv3"
BOT_IP = "192.168.1.15"
BOT_PORT = 12360

 app_user.yml:
ebot_ip: 192.168.1.15
ebot_port: 12360
mode: lan

 databases.yml
username: ebotv3
password: somepass

And also i don't understand this string =(
EXTERNAL_LOG_IP = "" ; use this in case your server isn't binded with the external IP (behind a NAT)

**Comment by CodersGit** [comment]
It's because your browser can't connect to your websocket server

**Comment by Pilik** [comment]
@CodersGit it's could be true, if they would not in one subnet.
--------
Okay, I add EXTERNAL_LOG_IP = "my IP"

Also I don't know that exacly cache do.
You you edit your config files you should clear cache by command 
`php symfony cc`
After that ebot working fine.
