### ISSUE TITLE
SQLSTATE[42000]

### ISSUE THREAD

**Issue by spot88** [deStrO/eBot-CSGO#141]
**SQL Server info:** 
Server: Localhost via UNIX socket
Server type: MariaDB
Server version: 10.0.31-MariaDB-0ubuntu0.16.04.2 - Ubuntu 16.04
Protocol version: 10
User: ebotv3@localhost
Server charset: UTF-8 Unicode (utf8)

Get this error when i try php symfony doctrine:build --all --no-confirmation. 
Using this guide: http://forum.esport-tools.net/d/2-how-to-install-ebot-on-debian-ubuntu-for-beginners

`SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes. Failing Query: "CREATE TABLE sf_guard_permission (id BIGINT AUTO_INCREMENT, name VARCHAR(255) UNIQUE, description TEXT, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = INNODB". Failing Query: CREATE TABLE sf_guard_permission (id BIGINT AUTO_INCREMENT, name VARCHAR(255) UNIQUE, description TEXT, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = INNODB  `

**Comment by spot88** [comment]
Gave up, installed Ubuntu 14.04 :(

**Comment by cabusar** [comment]
Hello,

Reason : MariaDB querry limit. (as i understand it)

Solution : use utf8 and not utf8mb4

Exemple with phpmyadmin in "operations" tab of the ebot db.

![image](https://user-images.githubusercontent.com/9006563/32696120-ae9a3516-c76f-11e7-9fcf-20bf79ea1f73.png)
 
Work for me, debian 9 and MariaDB.

Regards.

**Comment by hackertron** [comment]
hey @cabusar  i am using debian too , can you tell how to do it without phpmyadmin ?

**Comment by CodersGit** [comment]
@hackertron You want any another tool or an query?

**Comment by hackertron** [comment]
@CodersGit  my phpmyadmin is only working with php7 ( here i am using php5.6 because of requirements) .
i just want to fix that error not sure how

**Comment by CodersGit** [comment]
You can install older phpmyadmin's version manually or use something like a DataGrip/HeidiSQL

**Comment by hackertron** [comment]
alright i did something totally different , i don't know if it will work for others or not . I installed php7 then go to phpmyadmin , saved all the sql code from `/data/sql/schema.sql` into a local sql file. 

went to phpmyadmin changed setting as mentioned above by @cabusar  then imported the sql file . it executed without any errors

**Comment by CodersGit** [comment]
It seems like working, but not good solution

**Comment by hackertron** [comment]
yeah not good , i think it's not working good either . when i go to ip-here/ebot i get this page it's just empty page

![capture](https://user-images.githubusercontent.com/7667514/36349989-29e4c7e4-14b5-11e8-9bcd-7e3a0d53e37f.PNG)

**Comment by cabusar** [comment]
Sorry, busy at work.

For utf8 migration you could look here  
: https://docs.moodle.org/32/en/Converting_your_MySQL_database_to_UTF8

I have to do it just after mariaDB install and before ebot install.

@hackertron : could you paste me some log from your web server and/or php ?

**Comment by hackertron** [comment]
hey @cabusar i have solved the issue ( mentioned it on another issue , forgot to mention on this one). Technically i have not solved :/ i took easy approach . changed server to 14.04 so i no longer have any logs but on a bright side everything is working now :D
