### ISSUE TITLE
Unreliable csay demo upload

### ISSUE THREAD

**Issue by om22** [deStrO/eBot-CSGO#142]
I got a problem with csay uploading demos. If I restart my cs server it works everytime if I try from server console. After a match it doesn't work reliably. If I spam it to console it works in some cases but most of the time i have to restart my cs server for it to work.

- CSay version 3.2.5
- log of a match https://paste.ee/p/9974i

If I try  it after a match without restarting the server I either get

curl_easy_perform() failed: couldn't resolve host name
or
curl_easy_perform() failed: url using bad/illegal format or missing url

Restart cs server: boom working 10 of 10 times

**Comment by 33fraise33** [comment]
I'm seeing the same issue. I'm unable to upload my demos to my ip but if I do an api call test on the url it's trying to upload to, it is responding with a status 200.

For me it is not working after a restart though :/
