### ISSUE TITLE
sqlstate 42000 syntax error or access violation 1071 specified key was too long

### ISSUE THREAD

**Issue by hackertron** [deStrO/eBot-CSGO#146]
I am getting following error when i do php symfony doctrine:build --all --no-confirmation

i have made new mysql user too because default root was giving pdo connection error . 

how can i resolve it ?

error ![error](https://user-images.githubusercontent.com/7667514/36344988-c9e072d8-1448-11e8-8131-3a0a87239f02.PNG)

**Comment by CodersGit** [comment]
I think, #141 will help you

**Comment by hackertron** [comment]
okay for starters here is my config 

debain 9 , php 5.6 ( because of guide i am following ) , mariaDB 10.1.26 . 

i have set these things too in mysql 
`set global innodb_file_format = BARRACUDA;
set global innodb_large_prefix = ON;`

`SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.. Failing Query: "CREATE TABLE sf_guard_group (id BIGINT AUTO_INCREMENT, name VARCHAR(255) UNIQUE, description TEXT, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = INNODB". Failing Query: CREATE TABLE sf_guard_group (id BIGINT AUTO_INCREMENT, name VARCHAR(255) UNIQUE, description TEXT, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE = INNODB
`

**Comment by hackertron** [comment]
changed the setup to ubuntu 14.04 . solved now !!
