### ISSUE TITLE
eBot + CSGO installation on same server - demo not pushing to eBot Web

### ISSUE THREAD

**Issue by Flegma** [deStrO/eBot-CSGO#152]
Hello,
when CSGO and eBot is installed on the same machine, demo pushing is not working. 
If i try with a server thats not hosted on the same machine, demo is pushed on the web part of the eBot. 
So, eBot configuration (app_user.yml and config.ini) is okay (its working with outside server), in the logs i can see that the server executed the demo push command (csay_tv_demo_push) but the demo is not available if CSGO server is on the same machine as the eBot.

If i restart the server, and than use the demo push command, demo is pushed to the eBot web. 

In the server logs (before CSGO server is restarted) the error is: 
**curl_easy_perform() failed: Couldn't resolve host name**
Another error is:
**curl_easy_perform() failed: URL using bad/illegal format or missing URL**
And after the CSGO server is restarted, same command 
**csay_tv_demo_push "12_xenno-flegma_de_dust2.dem" "http://ip_of_the_server:12360/upload"
Speed: 12050582.000 bytes/sec during 0.444 seconds
Upload finished**

Im using Ubuntu 16.04 LTS, with:
root@testingarea:~# curl --version
curl 7.63.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

(I have manually updated cURL from 7.47 to 7.63 and it didnt help). 

Anyone have a solution? (maybe its libcurl or openssl problem)?

**Comment by CodersGit** [comment]
Is

**Comment by Flegma** [comment]
No. Its working when using outside server or when the server is restarted, so i dont see why would SSL on websocket help with this issue?
