### ISSUE TITLE
eBot skip the rounds!

### ISSUE THREAD

**Issue by nutellazpw** [deStrO/eBot-CSGO#157]
Hello! 
Today , i have match played on my ebot , and after 4-5 rounds , ebot start to skip result!
Example! Results is 4:0 for TT, and here is win for CT , and should be 4:1 , but after round end , ebot say to result is 4:2 (instead of 4:1)

Someone know how to fix this ?
Thanks!

**Comment by nutellazpw** [comment]
Solved: VPS Firewall problem. Don't use OVH for ebot :D

**Comment by datamendes** [comment]
I have the same issue. How did you fixed the problem?

I am also using OVH VPS.

**Comment by nutellazpw** [comment]
> 
> 
> I have the same issue. How did you fixed the problem?
> 
> I am also using OVH VPS.

Change ISP. Don't use OVH for stuff like this !

**Comment by datamendes** [comment]
but is it the most secure ISP.

Is there any solution that you know or the only solution is to change?
