### ISSUE TITLE
eBot rules file problem

### ISSUE THREAD

**Issue by TheNYte** [deStrO/eBot-CSGO#159]
Hey guys, i need your help , me and my friend are doing little tournament next week, and i set up the eBot on server that will be used for matches, e bot seems to work fine but when i use esl5on5 or tried to upload "my own" server config it is not loading properly, better to say, it doesnt load config at all.

**Comment by Romiesta** [comment]
Did you try to upload directly your via FTP on your game server ?

**Comment by TheNYte** [comment]
yes i updated all cfgs , with esl ones, and when i start server should i use exec esl5on.cfg? or i will not have time to change it when ill make new match in web UI so it souhld not change config after?

**Comment by Romiesta** [comment]
When you create a new match in the ebot’s web ui you have to specify the rules that you want. You can modify the default rules in the config. When the match is start and the 2 teams is ready, eBot load the rules that you have specified after the round

**Comment by TheNYte** [comment]
ill reply with some screens after i get home from work, i think the config didnt load cuz theres mp_roundtime set to 1.92 thats 1 min 52.2 seconds time for round and after we started the match there was 2 mins and 15 seconds per round so.

**Comment by Romiesta** [comment]
To be sure that the config is correctly loaded, you can put at the end :
Say « Config ESL Loaded »

Or something else :-)

**Comment by TheNYte** [comment]
ye i see. thanks. but youre sayin that it should load the right config after !ready after knife round?

**Comment by Romiesta** [comment]
Yes. !ready > knife round > !stay or !swap > !ready > 10 secondes > load config and live
