### ISSUE TITLE
Wingman Support

### ISSUE THREAD

**Issue by eoswald** [deStrO/eBot-CSGO#160]
Any plans for supporting wingman games?

Edit: Just realized the last commit was 3 years ago but I'll leave the issue up just in case.

**Comment by yahoo1999** [comment]
Hey, 
eBot is fully wingman compatible. The only thing you need to do is adding wingman maps to eBot's config.ini and put your CS:GO server in wingman mode (game_type 0; game_mode 2). Even though eBot wasn't designed with Wingman in mind, there shouldn't be any issues.

**Comment by eoswald** [comment]
Ah, thank you! I had the `game_type` and `game_mode` set in my live.cfg but not the server so all the buy zones were messed up. Setting the cvars on the server itself fixed it.

**Comment by yahoo1999** [comment]
Remember that not all the maps support wingman by default. For Dust, you need de_shortdust, and de_shortnuke for Nuke
