### ISSUE TITLE
What if pthreads doesn't want to work?

### ISSUE THREAD

**Issue by s1inche** [deStrO/eBot-CSGO#171]
What if pthreads doesn't want to work?

-----------------------------------------------------
| PHP 5.3.1 or newer    -> required  -> [ Yes ] 7.2.34-8+ubuntu18.04.1+deb.sury.org+1
| Standard PHP Library  -> required  -> [ Yes ]
| MySQL                 -> required  -> [ Yes ]
| Sockets               -> required  -> [ Yes ]
| pthreads              -> required  -> [ No ]
-----------------------------------------------------
| Your php configuration missed, please make sure that you have all feature !

What else do you need to throw off in order to understand the problem? Thank you in advance)

**Comment by vince52** [comment]
There is a bug with php 5 and pthread version.

**Comment by deStrO** [comment]
You need to install a custom version of PHP, not a provided one by distribution package :
https://github.com/deStrO/eBot-CSGO/blob/master/install.txt

eBot needs pthreads to receive and process logs at the same time.
