### ISSUE TITLE
eBot socket io connection refused for 176.31.211.228:12370 server

### ISSUE THREAD

**Issue by axent1** [deStrO/eBot-CSGO#172]
@deStrO  Can you please fix http://public.ebot.wedeho.be/
There is a problem with socket io connection so we can't manage matches stop/start etc.. we are getting socket io connection refused 

![image](https://user-images.githubusercontent.com/31309373/103344500-0e8f8e80-4a8f-11eb-95a3-9c171a53de95.png)

**Comment by agennari** [comment]
Got same error. 
I can start a match (and play the match) but, If I want to stop it or do something after, I got this error
