### ISSUE TITLE
how to completely end a match while its going on

### ISSUE THREAD

**Issue by vedalcs** [deStrO/eBot-CSGO#173]
i tried using the stopBack command but it doesnt work for me, how do you completely stop or end a match. Sometimes we play scrims and the teams we play against leaves early or we have to go early and i cant end the ebot match so it gets stuck on that one match.

**Comment by vedalcs** [comment]
and also the stop command which worked before via the ebot web page doesnt work anymore it just keeps on loading for me

**Comment by vince52** [comment]
Are you talking about ebot Public?

**Comment by vedalcs** [comment]
yes

**Comment by vedalcs** [comment]
> Are you talking about ebot Public?

yes, not much experience with ebot and servers
