### ISSUE TITLE
Server wont start or stop

### ISSUE THREAD

**Issue by Nicho99** [deStrO/eBot-CSGO#174]
Started my eBot server and nothing happened also cant even stop the matches it just a loading icon next to them. Using dathost followed the exact instructions.

**Comment by JimZach86** [comment]
I have the exact same issue on 2 matches. See pic for info.
pls help.
![2021-02-12 10_27_29-Window](https://user-images.githubusercontent.com/78955524/107750948-fca33b80-6d1c-11eb-918f-e32b66a03509.png)

**Comment by MikkelDK** [comment]
Yeah, there is a bug with public ebot.

I did setup ebot (as private) and can run any matches. without issue with starting. ^^

**Comment by JimZach86** [comment]
Hi,

Still seems to be a bug with the public one.

How to setup ebot as private?

Jimmi Zachariassen

Mobil +45 2333 1080 • zjimmi@hotmail.com

Fra: Mikkel <notifications@github.com>
Sendt: 15. februar 2021 20:04
Til: deStrO/eBot-CSGO <eBot-CSGO@noreply.github.com>
Cc: JimZach86 <zjimmi@hotmail.com>; Comment <comment@noreply.github.com>
Emne: Re: [deStrO/eBot-CSGO] Server wont start or stop (#174)


Yeah, there is a bug with public ebot.

I did setup ebot (as private) and can run any matches. without issue with starting. ^^

**Comment by MikkelDK** [comment]
@JimZach86 you need a vps, it need to run old php version plus pthreads before it's possible.

Eg Ubuntu 19 or Debian 10. Php need to be 5.2 i think.

**Comment by JimZach86** [comment]
Thx.

Is the public ebot/web portal going to work again or?

Jimmi Zachariassen

Mobil +45 2333 1080 • zjimmi@hotmail.com

Fra: Mikkel <notifications@github.com>
Sendt: 16. februar 2021 08:16
Til: deStrO/eBot-CSGO <eBot-CSGO@noreply.github.com>
Cc: JimZach86 <zjimmi@hotmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [deStrO/eBot-CSGO] Server wont start or stop (#174)


@JimZach86<https://github.com/JimZach86> you need a vps, it need to run old php version plus pthreads before it's possible.

Eg Ubuntu 19 or Debian 10. Php need to be 5.2 i think.

**Comment by MikkelDK** [comment]
> Thx. Is the public ebot/web portal going to work again or?

I don't think so.
It's just bugged since it's only @deStrO can stop the matches or restart the "bootstrap.php" :)

**Comment by JimZach86** [comment]
Aight, thx for the answers. Much appreciated 😊

Jimmi Zachariassen

Mobil +45 2333 1080 • zjimmi@hotmail.com

Fra: Mikkel <notifications@github.com>
Sendt: 16. februar 2021 14:03
Til: deStrO/eBot-CSGO <eBot-CSGO@noreply.github.com>
Cc: JimZach86 <zjimmi@hotmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [deStrO/eBot-CSGO] Server wont start or stop (#174)


Thx. Is the public ebot/web portal going to work again or?

I don't think so.
It's just bugged since it's only @deStrO<https://github.com/deStrO> can stop the matches or restart the "bootstrap.php" :)

**Comment by deStrO** [comment]
There were an issue with the new server and the amount of demo, it's fixed
:)

Le mar. 16 févr. 2021 à 14:23, JimZach86 <notifications@github.com> a
écrit :

**Comment by JimZach86** [comment]
Sounds good, thx.

I cannot stop my matches, could you please stop them? #4440 & #4462

[cid:7E04D1ED-8CFD-4732-ABCB-6B0EE04F487A]

Venlig hilsen
Jimmi Zachariassen

Den 17. feb. 2021 kl. 08.01 skrev Julien Pardons <notifications@github.com>:

﻿

There were an issue with the new server and the amount of demo, it's fixed
:)

Le mar. 16 févr. 2021 à 14:23, JimZach86 <notifications@github.com> a
écrit :

**Comment by MikkelDK** [comment]
> Sounds good, thx. I cannot stop my matches, could you please stop them? #4440 & #4462

Let me know, if you want a private setup, so you won't get the problem (in the future) ^^

It can take (hours/days/weeks) before, destrO can stop the matches on "main website" ;(

**Comment by JimZach86** [comment]
I Will.

Ok, I will remove it from the server so far then.

Thx Mikkel

Venlig hilsen
Jimmi Zachariassen

Den 17. feb. 2021 kl. 11.06 skrev Mikkel <notifications@github.com>:

﻿

Sounds good, thx. I cannot stop my matches, could you please stop them? #4440 & #4462

Let me know, if you want a private setup, so you won't get the problem (in the future) ^^

It can take (hours/days/weeks) before, destrO can stop the matches on "main website" ;(
