### ISSUE TITLE
Add Ancient Please

### ISSUE THREAD

**Issue by ProfessorXander** [deStrO/eBot-CSGO#177]
Hello, with the new addition of ancient into the map pool, it would be awesome if i could select to play it, thankyou

**Comment by vince52** [comment]
If you are using your own version of eBot, it is possible to change the map pool.

https://github.com/deStrO/eBot-CSGO/blob/179db02043bfb1ee775c70c6f23d0553f0536332/config/config.ini.smp#L35-L49
