### ISSUE TITLE
EBOT doesn't work

### ISSUE THREAD

**Issue by s1inche** [deStrO/eBot-CSGO#181]
EBOT gives this error at startup
`Fatal error: Call to a member function findFile() on a non-object in /home/ebot/ebot-csgo/vendor/composer/ClassLoader.php on line 427`
![image](https://user-images.githubusercontent.com/54583646/143561394-8a41c6d1-47a7-4f59-8aef-f8875370f502.png)

**Comment by 0BuRner** [comment]
Seems the Composer version you're using in incompatible with the eBot version or the PHP version. 
Try to downgrade Composer to an older version. If still not working, upgrade your PHP version.
