### ISSUE TITLE
How do I integrate eBot with my CS2 server?

### ISSUE THREAD

**Issue by ureeck** [deStrO/eBot-CSGO#185]
Need help. How to make eBot work on CS2 server?

**Comment by Iwhite67** [comment]
Not possible for the moment, Destro we make a update of Ebot for compatibility with cs2

**Comment by deStrO** [comment]
Almost done ... :) Logs are working, rcon is working, I'm checking for the plugin side now...

**Comment by ureeck** [comment]
Can't wait! 🫶🏻

**Comment by rpkaul** [comment]
Excited !!

**Comment by rpkaul** [comment]
can someone help me with new version v3.4 - CS2, in CSGO i was using that csay plugin in server and public panel
but in cs2 i dont know what to do.

**Comment by Iwhite67** [comment]
@deStrO if i understand

Srcds -> ebot project -> redis -> ebot CSGO <-> ebot web ?

**Comment by deStrO** [comment]
Yes that's the new "route" ;)

Server send via HTTP the logs to "ebot-project/logs-receiver"
Then the logs are dispatched on a redis-server to make a queue
And then it's all the same, as before.

Public panel isn't updated yet, I've to update it too ;)

**Comment by CoderGeek82** [comment]
Sometimes you gotta admit, old is gold. When everything else has fallen apart, eBot coming back to life for rescue. Let me know what can i do to contribute.

**Comment by ureeck** [comment]
Help me please! I'm trying to install eBot via install.txt and once I get to this point `/usr/local/bin/phpize` it says `-bash: /usr/local/bin/phpize: No such file or directory`. What did I do wrong? Everything was according to instruction.

**Comment by ureeck** [comment]
> Help me please! I'm trying to install eBot via install.txt and once I get to this point `/usr/local/bin/phpize` it says `-bash: /usr/local/bin/phpize: No such file or directory`. What did I do wrong? Everything was according to instruction.

Please @deStrO could you update the install.txt guide for noobs like me? 😔

**Comment by nyambaatar** [comment]
ebot serverside plugin updated for cs2 ?

**Comment by rpkaul** [comment]
@nyambaatar yes and you can download it from his discord server

**Comment by wanderchannel** [comment]
When you are going to  Update the Public Panel http://public.ebot.wedeho.be/ ?

Because in 3 Week Time im gonna have a LAN Event and i Need it to work in my LAN Server , i tried to create the website in my PC but i cant put it to work 

kind regards

**Comment by deStrO** [comment]
The public version has been updated for CS2 .
Closing this issue.
