### ISSUE TITLE
CSay causing Segmentation Fault on Linux DS

### ISSUE THREAD

**Issue by ryandotnet** [deStrO/eBot-CSGO#194]
Hello! 

Installing CS2 CSay plugin will cause my Linux DS to throw a Segmentation Fault. Tested on Ubuntu 22.04 / 24.04 & Debian 12.5.

Using the latest version of Metamod. Removing the plugin allows the server to launch (with Metamod) with no issues. 

eBot still works, but functions like demo uploading, damage print and the eBot prefix doesn't work properly. 

Could this please be looked into? If you require any further information, please let me know.

Thanks!

**Comment by deStrO** [comment]
Hello,

A patch is on the way, I'll make an announcement on Discord when it's released

**Comment by ryandotnet** [comment]
> Hello,
> 
> A patch is on the way, I'll make an announcement on Discord when it's released

Thanks deStrO! For all the hard work you've put in and for continuing to do so. I will keep an eye out on Discord and close this issue for now.

**Comment by SeriousVitamin** [comment]
Hello, @deStrO! We want to start a small tournament in the next month. Can you tell me approximately when the patch will be? Thanks for the answer.
