### ISSUE TITLE
Force knife on knife round

### ISSUE THREAD

**Issue by BatStak** [deStrO/eBot-CSGO#29]
Here is a solution to force knife on knife round.
Edit file /src/eBot/Match/Match.php
We have to set mp_startmoney to 0 to be sure they buy nothing.
This cvar is probably 99% set in match cfg.

http://pastebin.com/K9H8adHT

Lines 1367, 1368, 1384, 1385, 2721, 2757

**Comment by trinialol** [comment]
I made a new fix for everyone. :)

https://github.com/deStrO/eBot-CSGO/issues/60
