### ISSUE TITLE
full installation manual

### ISSUE THREAD

**Issue by d4wgh** [deStrO/eBot-CSGO#31]
Hi , is there anywhere i can find a step by step installation guide to this e-bot?
Or is there anyone who could guide me through it?

**Comment by sqrtroot** [comment]
hi man
don't know if you fixed it already.
But to execute a command you should open a command prompt at the location of the nodejs.exe folder. (press shift and then left click in the folder. there will be a extra option open command window here). and then you should write "nodejs.exe [command]" in the commandprompt and execute that
