### ISSUE TITLE
Switch teams

### ISSUE THREAD

**Issue by Fidelix** [deStrO/eBot-CSGO#42]
While I was playing with my friends on a LAN game, in the middle of the match - when it was time to switch teams - everything simply paused.

I tried every command I could and every option available on the web interface, but the game remained frozen.

Do I have to do anything special to switch sides?
Also, statistics were not appearing on the web interface...

**Comment by deStrO** [comment]
It seems eBot and your game server didn't communicated. What was your configuration? :)

**Comment by Fidelix** [comment]
This was a problem with steam.
