### ISSUE TITLE
Table 'dbebot.matchs' doesn't exist

### ISSUE THREAD

**Issue by BlueXik** [deStrO/eBot-CSGO#45]
-> NEVERMIND, I've been following 2013 tutorial, and didn't install eBot-Web -.-

Hello there !
I've got problem with starting eBot on ubuntu 14.04 (digitalocean.com).
When I try to run "php bootstrap.php" everything seems to be okay, but it stops with 

Table 'dbebot.matchs' doesn't exist
(dbebot is my database)

I guess it's just misspelled "matches" but I just can't find the file where it is located :/

Thanks for help...

**Comment by iTsFILIPOficial** [comment]
Hey @BlueXik using the Ebot-Web Run the [SQL File](https://github.com/deStrO/eBot-CSGO-Web/blob/master/data/sql/schema.sql) and see if the table gets created.

**Comment by Nols1000** [comment]
Please close this issue if you dont have this issue anymore.
