### ISSUE TITLE
How to install pthreads on ubuntu 14.04?

### ISSUE THREAD

**Issue by DieQuelle** [deStrO/eBot-CSGO#54]
Can you explain me how to isntall pthreads on ubuntu 14.04

Versions:

```
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
Linux eBot 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Digital Ocean LEMP Server (pre builded "Application")

PHP Test:
PHP 5.3.1 or newer    -> required  -> [ Yes ] 5.5.9-1ubuntu4.14
Standard PHP Library  -> required  -> [ Yes ]
MySQL                 -> required  -> [ Yes ]
Sockets               -> required  -> [ Yes ]
pthreads              -> required  -> [ No ]

```

**Comment by HalfEatenPie** [comment]
apt-get install libpthread-stubs0-dev

**Comment by DieQuelle** [comment]
Does not work for me.
I installed it restarted all services even a reboot wont help.

**Comment by rmrhz** [comment]
Could you show at least an error log?

**Comment by DieQuelle** [comment]
Why error log, the check is in my start post?!

**Comment by rmrhz** [comment]
After you tried `apt-get install libpthread-stubs0-dev`

**Comment by SkullMasher** [comment]
The Package has been install correctly on my side (debian sid if that matters) and did not solve the problem. The libpthread package are for the libC. I'm pretty sure you need to have the php pthread for the ebot to work. 

PHP.net doc about the pthread : https://secure.php.net/manual/en/book.pthreads.php

Will report back once i'm done with making php pthread works.

**Comment by SkullMasher** [comment]
So I ended up taking the version of ebot without the pthreads by doing a git checkout master after the initial git clone.

I don't want to recompile php on this server only for the ebot at this time. I would like to have additional information from the maintainer about pthreads in eBot.

I will certainly add/enable zts and pthreads once I got my head around php7 which at this time require a manual php compilation on debian. I do not have time for that at the moment.

**Comment by SkullMasher** [comment]
I ended with the server randomly droping 'Can't auth to rcon' after some time. We did no go farther than the knife. I'm assuming the old version is broken or something. Will try the pthread one.

**Comment by DieQuelle** [comment]
@SkullMasher 
Hey. Nice that somebody has the same problem as me.
After this problems i tried the .deb package which installed the most ressources.

After this i get:


php boostrap.php
```
-----------------------------------------------------
| Registerung Shutdown function !
| Starting eBot Websocket-Server !
| WebSocket server crashed
-----------------------------------------------------
```

or via /etc/init.d/ebotv3 start -> status -> not running.

**Comment by SkullMasher** [comment]
deb package is vastly outdated I don't know if you can make it work.

Does your package even have some sort of websocket_server.js ? If that's the case you'll have to check for nodejs log.

I'm planning a php migration on this week end. I'll come back to you later about the pthread installation and how it goes.

**Comment by DieQuelle** [comment]
Did you find a way to get it working?

**Comment by codelpech** [comment]
did you found the solution ?
