### ISSUE TITLE
How to set in game ebot ?

### ISSUE THREAD

**Issue by ixayldz** [deStrO/eBot-CSGO#56]
Hi myfriend. İ want use ebot like this. if its possible can you tell me how i set i realy thank you..

example: i install e bot to my community game server 5on5 match server.

i want 10 player joined the game. after joined 10th. player to server auto map vote start
and players vote map after they choice to map map change and again 10 player enter the server than ebot make 2 random team  knife round and match start. And after match ebot send to website  match stats. is it possible to do with ebot ?

**Comment by Nols1000** [comment]
its not possibil with the eBot as it is in this repo.

**Comment by ixayldz** [comment]
i want smilar system with esea or faceit. There is any mod plugin or something connection with web?

**Comment by HalfEatenPie** [comment]
No.

**Comment by Nols1000** [comment]
yaeh u can view: https://github.com/deStrO/eBot-CSGO-Web
this is the web interface of the ebot.
