### ISSUE TITLE
Mysql setup error

### ISSUE THREAD

**Issue by SM411** [deStrO/eBot-CSGO#57]
Hi,
I will start by saying my experience with Linux is rather limited, so this might be a trivial issue just due to my lack of understanding.

What I have done is following your tutorial:

https://github.com/deStrO/eBot-CSGO/blob/threads/install.txt

I have a fresh Ubuntu Server 14.04.3 LTS. Nothing is installed other than what is written in the tutorial. Setup is done as root.

I did install mysql-server and created a db called ebotv3 with a user ebotv3 and password ebotv3.

When I try to run:

`php5 symfony doctrine:build --all --no-confirmation`

I get this error: 

 Couldn't locate driver named mysql.

I also got an error when running the:

`curl -sS https://getcomposer.org/installer | php5`

But that was fixed by running apt-get install php5-**\* (dont remeber the excact letters) as suggested by the OS.

Can you please point me in the right direction :+1:

**Comment by mavrick** [comment]
you may need to run

``apt-get install php5-mysql``

If it complains that mysql server is missing then you will need to run

``apt-get install mysql-server php5-mysql`` 

and follow all the prompts

**Comment by SM411** [comment]
Thank you for the help. This got me one step closer to get it running. But as I have learned, there is allways another challenge when working with this project. My next problem is that I get a php-error when trying to acess the panel.

`<?php


require_once(dirname(__FILE__).'/../config/ProjectConfiguration.class.php');

$configuration = ProjectConfiguration::getApplicationConfiguration('backend', 'prod', false);
sfContext::createInstance($configuration)->dispatch();`

Anyone familiar with this?

**Comment by mavrick** [comment]
Are you able to post the error that you are getting?
