### ISSUE TITLE
My webserver-host doesn't allow me to run .bat files. What to do?

### ISSUE THREAD

**Issue by Leducia** [deStrO/eBot-CSGO#59]
I cannot run .bat files on my webserver as my host doesn't allow it. What can I do? Do you know any host who allows .bat files to be ran?

**Comment by sirtobey** [comment]
.bat files are specific to Windows operating systems. What OS are you running at your hoster?
If you have NodeJS on the server and it's running on Linux, you don't need the .bat file.

**Comment by Leducia** [comment]
Well what do I type into my Putty then, to make it start the socket server?

**Comment by Leducia** [comment]
My eBot files is on a Ubuntu linux server, and I'm using Putty to remotely accesing the shit on there

**Comment by Leducia** [comment]
More info:

When I type "node websocket_server.js" into Putty, it says:

Option log level is not valid. Please refer to the README.
Server is listenning on port undefined
UDP Server listening on 0.0.0.0:50448

**Comment by HalfEatenPie** [comment]
Hello, 

Please check to make sure ebot is running on the port defined by running netstat -a .

**Comment by Leducia** [comment]
It doesn't list the given port. Do you know a fix? Would be much appreciated. =)

**Comment by mavrick** [comment]
@Leducia you need to follow the installation instructions outlined here: https://github.com/deStrO/eBot-CSGO/blob/threads/INSTALL.md
