### ISSUE TITLE
Kniferound-Fix!

### ISSUE THREAD

**Issue by trinialol** [deStrO/eBot-CSGO#60]
Hello guys,

I just made a fix for the Kniferound, which applies all players within the kniferound free armor, sets startmoney to 0, removes pistols, etc.

Here's the link to the Pastebin: http://pastebin.com/X4Af1ETp

I hope you guys enjoy this fix :)

**Comment by KoSoVaR** [comment]
As helpful of a fix this is - you should fork / do a pull request, or if you're going to work on other pieces, do a fork and I'll definitely come on over :)  Really wishing more dev was done around this.

**Comment by trinialol** [comment]
I guess deStrO mentioned somewhere, that the fix is already in the eBot 4.0. But I think he mentioned that in year 2015 (somewhere in september or something, idk^^). But yeah, I'm gonna do a Pullrequest soon for it. Also tweeted already to deStrO, and told him that I posted a fix for the kniferound :)

**Comment by Janhouse** [comment]
Seems to be fixed in master version, please close this.
