### ISSUE TITLE
Do you have a SQL string I can run in my phpmyadmin to create the needed database structure?

### ISSUE THREAD

**Issue by Leducia** [deStrO/eBot-CSGO#61]
I don't want the admin panel which comes with eBot, I'm going to create a whole other system. Anyways, I need the database structure needed for eBot to work, but I dont feel like installing the admin panel, just to get this.

Bottom line: Do you have a SQL string I can run in my phpmyadmin?

Best regards, Per Hansen

**Comment by trinialol** [comment]
I could upload you the empty Database SQL if you want, then you would have the structure :)

**Comment by Leducia** [comment]
Empty database structure would be really nice! :)

**Comment by Leducia** [comment]
Empty database structure would be really nice! :)

**Comment by trinialol** [comment]
http://pastebin.com/dT4hWHGL

There you go :)

**Comment by Leducia** [comment]
Thanks alot!
