### ISSUE TITLE
Match Medic issues

### ISSUE THREAD

**Issue by KoSoVaR** [deStrO/eBot-CSGO#62]
Match medic does not work properly at round 15 and 16.  Say the score is 8-6 and match is paused at round 15, I try to match medic to the previous round and a whole lot of nothing happens. Repeated use of the restore button will yield very odd behavior such as everyone's dead, guns all over the map, etc.

Same thing happens on round 16, there seems to be an issue where the teams get switched wrong but money is correct.

Is it possible to manually use the mp restore command from the raw Csgo logs vs the ebot logs or a) are these the same and b) will stats track correctly?

**Comment by trinialol** [comment]
Hey, are you using the public version, or did you install the eBot on your Windows/Linux-Server? If you installed it on your server, you should try to re-install it. The eBot works perfectly for me, it doesn't do anything wrong.

Just write me back here :)

**Comment by KoSoVaR** [comment]
I've definitely installed it on my own Linux machine.  I ran a recent tournament and you can see some of the matches here:

http://begolli.com/wcl2015/

If you go to Matches in Progress: http://begolli.com/wcl2015/matchs/current/1 - the 15 - 7 and 9 - 5 matches were irrecoverable.  There were rolling power outages and eBot Match Medic, while it worked, really saved the day.  

I've tried using this repo as well the fork from madmatt - https://github.com/madmatt/eBot-CSGO

**Comment by trinialol** [comment]
Alright, you could try to install it via the Debian-Package, if you haven't tried yet.

http://www.esport-tools.net/ebot/install

I guess you also have installed NodeJS, as you are running already eBot :) Just try it, and tell me if it worked for you. I also installed eBot via the Debian-Package, and everything is working fine for me :)

Just write me back here.

**Comment by KoSoVaR** [comment]
Ah interesting I did not try the Debian package. I did a custom install in
Ubuntu 14.04

**Comment by trinialol** [comment]
You should use Debian for eBot, or there will be problems, I guess.

**Comment by KoSoVaR** [comment]
That is a very closed way to look at this.  The source is available for download in the repo and it shouldn't differ from the package that is being offered for Debian.  The install steps are clear enough to get a working eBot + web panel as I've done it over 3 times now and experienced the same issues on all 3 instances.

This is science, not magic my friend.

**Comment by trinialol** [comment]
I don't know, I don't have any problems on Debian 7 64Bit. You should really try Debian :)

**Comment by KoSoVaR** [comment]
Definitely a few different noticeable things in at least the web area when using Debian - specifically the admin panel when looking at matches in progress.  The "latest release" on github has the stop/restart action items as a popup menu when you click on a match, where the UI for that is now on the right. 

I haven't done any diffs on the code, but I am going to try and run this way this evening to see if the match medic things are "fixed" in this "old" version (the site even says, not latest). 

If it is different, I'll try to track it down and figure out what...

**Comment by trinialol** [comment]
It doesn't have to be the latest version (debian package). I just can say, that it works perfectly for me with the debian package. Even if it's not the latest one. I also got a new server today, and installed eBot v3.1 again with the Debian-Package. Still works perfect for me.

**Comment by KoSoVaR** [comment]
Have you specifically tried to replicate the issue I referenced?  A 10 man, or 5v5 scrim, or whatever - go to round 15 of real play and try to match restore to round 14.  Or go to round 16 (when teams flip sides) and restore to 15...

Did you actually try this?

**Comment by trinialol** [comment]
Oh damn, I fully missunderstood you.. just add me on Steam, so we can talk easier. Let's figure a way out, how to fix it.

http://steamcommunity.com/id/Triniayo

**Comment by KoSoVaR** [comment]
For some closure, but not a fix to anyone who sees this thread, the Debian package is outdated and not up to snuff with the latest source.  There are UI changes as stated above.  And actually, if you restore > 1 time, eBot will crash (socket I believe crashes..).  Round 15,16 restore does not work.

The restore is at https://github.com/madmatt/eBot-CSGO/blob/develop/src/eBot/Match/Match.php line 2629...

**Comment by deStrO** [comment]
I already saw that kind of issues before, sometimes a round is counted twice and it's un-fixeable for now in live.

**Comment by KoSoVaR** [comment]
deStrO, do you know in what cases this happens?  Also does 3.2.0 fix any of this stuff?
