### ISSUE TITLE
Ebot 4.0 ETA ?

### ISSUE THREAD

**Issue by radiumx3** [deStrO/eBot-CSGO#64]
Hi, just seen you refered to a Ebot 4.0 future version, any ETA ?

**Comment by KoSoVaR** [comment]
He has stated that no work has begun on 4.0 (complete rewrite).

However he does have 3.2.0 threads version (core) that is unreleased.  Unsure of the reason to hold it back unless monetary.  Something better will come along sooner than later.  This project barely works anymore, not updated, and is dead.  Privately maintained probably for monetary purposes.

I'm not bashing the developer, if he is making money in any capacity selling to DreamHack or other LANs, then good on him.

But at least stop telling the community it is "coming".

**Comment by deStrO** [comment]
I updated to the last version for the eBot-WEB part.
The bot itself doesn't have any changes.

For the V4, I don't have any ETA because I'm working on several projects.

**Comment by 0BuRner** [comment]
> Re: Coming up next in eBot 4.0
Postby deStrO » 26 January 2016, 21:17
I'm not dead, I'm working on new project and I don't have time for eBot.
I'm thinking to release the current eBot core and search for community dev to make the "web" part.

Seems a bit contradictory to what you say... So what's the truth ?
Is there a core part you will share/release publicly soon or not ? What about the web part ?

As KoSoVaR says, don't let the community wait if nothing will come out...

**Comment by KoSoVaR** [comment]
Very contradictory.  According to this page http://forum.esport-tools.net/viewtopic.php?f=6&t=221&start=30 deStrO states, "I'm thinking to release the current eBot core and search for community dev to make the "web" part.".

**Comment by YannKr** [comment]
Is there a chance to get two version that are properly working together without using the ancient deb package?

**Comment by deStrO** [comment]
I'm checking currently to make a new deb package with the current working version.

I found a way to install php + threads in a unique command, I'm testing it asap and building the package if it works :)

**Comment by YannKr** [comment]
Hey Destro, I actually spent quite some time putting the bot into docker with pthreads. Got it working but I'm just afraid the codebase I got is not stable (I tried 3.1 and directly from master). The web version is also tagged 3.0 in it's latest release so hard to tell it will work with the v3.1 or master bot.

Here's the Dockerfile:
`FROM php:5-zts

ENV DEBIAN_FRONTEND noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y wget nano git unzip npm nodejs
RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN npm install socket.io@0.9.12 archiver formidable
RUN wget http://pecl.php.net/get/pthreads-2.0.10.tgz -O /usr/src/php/ext/pthreads.tgz
RUN cd /usr/src/php/ext/ && tar xvfz /usr/src/php/ext/pthreads.tgz

# Install pthreads
RUN docker-php-ext-install pthreads-2.0.10 pdo_mysql mysql sockets
RUN echo 'date.timezone = Europe/Paris' >> /usr/local/etc/php/conf.d/timezone.ini

RUN mkdir /ebot
WORKDIR /ebot

# Install composer
RUN php -r "readfile('https://getcomposer.org/installer');" > /ebot/composer-setup.php
RUN php -r "if (hash('SHA384', file_get_contents('/ebot/composer-setup.php')) === 'fd26ce67e3b237fffd5e5544b45b0d92c41a4afe3e3f778e942e43ce6be197b9cdc7c251dcde6e2a52297ea269370680') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('/ebot/composer-setup.php'); }"
RUN cd /ebot/ && php composer-setup.php
RUN php -r "unlink('/ebot/composer-setup.php');"

# Install eBot
RUN wget https://github.com/deStrO/eBot-CSGO/archive/v3.1-threads.zip -O /tmp/ebot.zip
RUN unzip /tmp/ebot.zip && rm -v /tmp/ebot.zip
RUN cp -rvp /ebot/eBot-CSGO-3.1-threads/* /ebot/ && rm -rf /ebot/eBot-CSGO-3.1-threads/
RUN php composer.phar install

# Cleanup
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["php", "bootstrap.php"]`

a simple docker build and docker run like this, would do`docker run -d -p 127.0.0.1:12360:12360 -p 127.0.0.1:12360:12360/udp --restart=always --name ebot \
  -v `pwd`/logs:/ebot/logs \
  -v `pwd`/demos:/ebot/demos \
  -v `pwd`/config:/ebot/config ebot`
(probably don't need to forward the tcp port).
Put the config files in `pwd`/config and you are good to go.

I then configured the web part on the docker host directly (didn't put it in a container yet).

Happy to continue that work if I get a pair of versions that work without too many bugs :)

**Comment by radiumx3** [comment]
@deStrO unrelated question but why we've got a limitation on 64 simultaneous  server instances managed by ebot, and how can we overcome this ? do we really need to duplicate ebot server and ebot database ?

**Comment by deStrO** [comment]
With an "instance" mode, a kind of multiple instance on the same database server where eBot manage match only with his instance id. It's not public. Maybe with the 4.0 it will be easier to do.

**Comment by radiumx3** [comment]
@deStrO this version is not released yet is it ? any mean to find it somewhere ? :woman:
