### ISSUE TITLE
!help, !rules (and maybe other stuff)

### ISSUE THREAD

**Issue by carazzim0** [deStrO/eBot-CSGO#65]
Hi guys, maybe you can help me.

I successfully set up my eBot-server and eBot-web with SSL and the very important commands like "!ready" and "!notready" are working as expected.

But for commands like "!help" and "!rules" just nothing happens.

Is there something I missed, or am I doing something wrong?

cheers,
carazzim0

**Comment by deStrO** [comment]
Check if you have the CSay plugin enabled on your server.

!help and !rules command works only with it

**Comment by carazzim0** [comment]
Hi deStrO,

thank you for your quick answer.

I just made ja quick video of what I mean. CSay works fine, but some commands do not.

Just 15 seconds to demonstrate what I mean:
https://youtu.be/SuEVTsfAlI0

**Comment by deStrO** [comment]
It's because you have a sourcemode plugin who override those command, that's all.

**Comment by carazzim0** [comment]
Hi,

I completely removed the sourcemod and metamod folder from our gameserver but those 2 commands still won't work:

https://www.youtube.com/watch?v=hsAqev49JHo

**Comment by jackhold** [comment]
i can confirm this newly installed server and those 2 commands don't work

**Comment by theantihero** [comment]
I can confirm this too. Sourcemod is not installed only CSay. Those commands do work, but does not output in chat ;).

**Comment by udni** [comment]
The only addon I have in csgo is the CSay plugin and I am having the same problem.
Would be really awesome if you could tell us how to fix it.

![873a4a00777b5fa3fe4d637ec7bcbdea](https://cloud.githubusercontent.com/assets/13217593/13941339/fffbd53e-efe6-11e5-852d-910c0447df3a.png)

**Comment by theantihero** [comment]
Replace csay_to_player with a sourcemod command in the Match file in ebot src. That will temporarily fix the issue. Im sure its a csay plugin issue and they have to update it or something. It could be eBot idk.

**Comment by udni** [comment]
What sourcemod command??

 Thanks!

**Comment by theantihero** [comment]
I think sm_psay to private message a player

**Comment by deepsh4h** [comment]
change your ip from BOT_IP = "127.0.0.1" to your public ip in **ebot-csgo/config/config.ini** 
This worked for me. Hope it helps

**Comment by carazzim0** [comment]
This was fixed with a csay update quite a while ago
