### ISSUE TITLE
Problem with CSay plugin

### ISSUE THREAD

**Issue by TiREX69** [deStrO/eBot-CSGO#66]
Hi,
i have latest csgo engine and csay plugin without other plugins.
And i have problem with commands because when i say "!help", "!map", "!rules" server can't give me response.

Regards
Szymon

**Comment by deStrO** [comment]
Hello,

Can you check if commands are well sent to the server in your CSGO logs?

**Comment by TiREX69** [comment]
Commands from CSGO-Bot (not CSay)?
I think not, because i test bot on tested website offer by you and bot good work.

I install CSGO-Bot from github install.txt

**Comment by TiREX69** [comment]
Okay i fix it.

**Comment by udni** [comment]
Could you let us know what you did to fix it??
I am struggling with the same problem, and yes it appears in the console output of my csgo server.
![873a4a00777b5fa3fe4d637ec7bcbdea](https://cloud.githubusercontent.com/assets/13217593/13941222/e02fe9b2-efe5-11e5-86ce-3e747cf22876.png)
