### ISSUE TITLE
Your php configuration missed, please make sure that you have all feature ! (MYSQL - NO)

### ISSUE THREAD

**Issue by jhuhes** [deStrO/eBot-CSGO#69]
![dfdsfdsf](https://cloud.githubusercontent.com/assets/18000989/13964043/fc7b1ca2-f078-11e5-936a-caae854ee735.PNG)

**Comment by hockeynQrdeN** [comment]
Take care with that 

`all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.0.0.1;dbname=ebotv3'
      username: root
      password: WEhIB1ko`


http://83.217.25.206/ebot-web/config/databases.yml
