### ISSUE TITLE
Ebot counting twice 

### ISSUE THREAD

**Issue by CorbetRobin** [deStrO/eBot-CSGO#72]
Good evening lads, the ebot is pooping on me right now.
i'm testing a game with a friend and when I kill him (at some point of the game, it's random) 
the bot is counting twice the win. (instead of 4-5 for example, it shows 4-6 and it shoudn't).

I don't know what to do, is it me or is it the bot ?

**Comment by mgjuhler** [comment]
Why closed? problem solved?

**Comment by CorbetRobin** [comment]
Look like it was just a network problem, an issue somewhere in our network cause the server to receive the command twice. So not a problem coming from eBot itself.

**Comment by nutellazpw** [comment]
I have this problemm to, how i can fix this
