### ISSUE TITLE
Knife round like a pistol round

### ISSUE THREAD

**Issue by rodolphonetto** [deStrO/eBot-CSGO#73]
hi my brother, iam using a esl5on5 .cfg file to my server and when we starts a knife round, the players get a pistols, c4 and etc, only the time round is correct... i need to do something? 

If someone wins this "Knife round" they can select !stay or !sweet.. but and cant made that they have only kevlar and knifes =/

[esl5on5.cfg.txt](https://github.com/deStrO/eBot-CSGO/files/190688/esl5on5.cfg.txt)

**Comment by metalbr** [comment]
I saw an issue here and a guy uploaded a match.php but for me this file crashed eBot with some websocket error... Then i copy the part above //map start and WORKED FINE for me :D :D :D thx very much
[Match.txt](https://github.com/deStrO/eBot-CSGO/files/190751/Match.txt)
