### ISSUE TITLE
Automatic Team Assigment

### ISSUE THREAD

**Issue by damiansky** [deStrO/eBot-CSGO#75]
Hello ,

Is there a possibility that i can automaticly assign player  to the team of my choosing like on Faceit for example , so the players dont have option to change teams CT/T and are matched automaticaly with their teams according to the players list on my webpage?

**Comment by ragnos** [comment]
Since eBot only uses the CSay-Addon (sometimes not even that), there is no way to force a team assignment. FaceIt does that with their own programming using SourceMod. If you google around you will find public sourcemod plugins doing exactly that, but even they struggle to get a reliable team assignment during special gamestates like halftime.

Long story short, not possible with eBot unless someone writes a new CSay-VSP or equivalent SourceMod-plugin, which could recieve a complete list of allowed players/spectators, store them on disk (in case of sudden server failure, eg. power outage) and finally force the players into their teams

**Comment by ax3rs** [comment]
@ragnos 
FACEIT don't use sourcemod, they use a modded version of eBot, both for website and server.
To do this so, you need to build an external Sourcemod plugin (what you want to do is pretty easy) and configure the eBot website + instance to work with the whitelist and arrange the players as you did.
The website part and the sourcemod part is pretty easy, the biggest problem is integrating this with the instance.
Maybe he will add it in eBot 4.0.

**Comment by jfkz** [comment]
@ax3rs 
I meet same problem. I will start coding my team automated plugin today. Could I ask you to share any info if you found it?

**Comment by ax3rs** [comment]
@jfkz 
I actually did it and it worked perfect, but I already replaced eBot with a heavily custom Get5 until eBot 4.0 will come out. About the files - my computer got literally destroyed this week, but if I could save the hard drive / those specific files, I will make a pull request with the files and what to do with them.

**Comment by jfkz** [comment]
@ax3rs 
Thank you for response! Wish you can restore all data soon. Can I provide any help for you? =)

**Comment by ax3rs** [comment]
@jfkz 
Nah, i just hope that the guy I payed for could restore, meanwhile, stuck on a shitty MacBook :/
Anyways, I will get some info in the next couple of days.

**Comment by jfkz** [comment]
@ax3rs
Thank you! Keep in touch.

**Comment by deStrO** [comment]
This feature is a kind of commercial feature as it has been requested from multiple companies and I can't release it due to commercial license. Sorry guys but for now I can't maybe in the next version! :)

**Comment by jfkz** [comment]
@deStrO
Thanks for clarifying. Another question: is there any rcon command to tie steamid to any team or we should always check it or use any sm plugin?

**Comment by jfkz** [comment]
@deStrO
Anyway, your bot is pretty good, keep going your way!

**Comment by deStrO** [comment]
No there are no default RCON command. I've builded some with a custom and private version of CSay (for the same reason, I can't publish it)

**Comment by jfkz** [comment]
@deStrO
Thanks man!

**Comment by jfkz** [comment]
@ax3rs 
Any updates? I took a glance at get5 and it looks so well.

**Comment by ax3rs** [comment]
@jfkz 
Everything was completely destroyed, they only managed to get half of my SSD restored, everything else got completely destroyed, I will see if the guys that I did it for them can send me the files, if not, it is lost, sorry.

**Comment by jfkz** [comment]
@ax3rs 
Understand you. My appologizes to your data.

**Comment by Technoblazed** [comment]
Sucks that this isn't available :/
