### ISSUE TITLE
Demo not available on public part of ebot

### ISSUE THREAD

**Issue by mog54** [deStrO/eBot-CSGO#78]
Hi, 

i don't understand why demo files aren't uploading to public part of ebot.
the demo file is going from csgo server to ebot server (home/eBot-CSGO/demos/), i can find in sql tables (under maps part) the match wich was played, and the "setting" demo in these table is the name of the demo, but on public part i saw anything :(

someone could help me please?
![capture](https://cloud.githubusercontent.com/assets/17116568/14590292/24939c86-04f7-11e6-9f14-d8469f469925.JPG)
![csgo server](https://cloud.githubusercontent.com/assets/17116568/14590293/2493d14c-04f7-11e6-8369-77b951ca5d87.jpg)
![ebot server](https://cloud.githubusercontent.com/assets/17116568/14590291/2493ab90-04f7-11e6-9d22-1dccc8c6ef90.jpg)
![ebot web](https://cloud.githubusercontent.com/assets/17116568/14590294/2493f1c2-04f7-11e6-9850-8f4e416d3ac8.jpg)

**Comment by mgjuhler** [comment]
Is the bot and web hostet on the same machine?

**Comment by mog54** [comment]
Yes evrything is on the same VM. I should try to separate ?

**Comment by mgjuhler** [comment]
No its fine, 
Picture 1 (bot log) check the bot ip, try it in a browser (due to timeout)

In "/var/www/html/config/app_user.yml" set logs and demo path so web page can find them (This is not described in their documentation)

```
log_match: /home/ebot/logs/log_match
log_match_admin: /home/ebot/logs/log_match_admin
demo_path: /home/ebot/demos
```

Remember to run 
`php symfony cc`
on the webserver. in the /var/www/html dir

I had the same demo/log error and this fixed it for me.

**Comment by mog54** [comment]
Thanks i'll try it

My path to web part is /usr/share/eBot-WEB/web/ 

No problem with that?

**Comment by mgjuhler** [comment]
Use your own path, i just made a copy paste from my system :)

**Comment by mog54** [comment]
I complet app_user.yml when i've installed ebot but for demo and log path i don't put the first "/" ! I wrote like thath: démo path => home/eBot-CSGO/demos 
That's probably just that

**Comment by mgjuhler** [comment]
Does it work now?

**Comment by mog54** [comment]
I'm at work i Will try in few hours :)

**Comment by mog54** [comment]
it's working !

thanks men !

but i have this error now ....

the tv_stoprecord and exec server.cfg commands are succesfuly execute on CSGO server, but ebot tell me that timed out  
![ban](https://cloud.githubusercontent.com/assets/17116568/14609445/1fea79d2-058a-11e6-9837-4f436b5e3274.JPG)

**Comment by mgjuhler** [comment]
I get the same error but the demos is being uploaded

**Comment by mog54** [comment]
Ok so it's a bug 

Thanks man
