### ISSUE TITLE
Kniferound

### ISSUE THREAD

**Issue by Barclis** [deStrO/eBot-CSGO#79]
Hi everything is working fine on my server. I only have one Problem. The players are having guns in the kniferound but I couldn't find the match.php to change this. Can someone help me?

**Comment by Versatile-BFG** [comment]
https://github.com/heew/eBot-CSGO/commit/6c14b9b0cff5060dd1dbd6e0040727a287b2ef6a

**Comment by Barclis** [comment]
Where do i have to put this?

**Comment by Versatile-BFG** [comment]
thats the match.php file. you can edit it and then restart the bot and it should use the new settings.

**Comment by Barclis** [comment]
i cant find the match.php. Maybe I have only installed the web bot

**Comment by mgjuhler** [comment]
Its not a web bot, its the bot script.

**Comment by Versatile-BFG** [comment]
where you have your ebot bot setup [not the web part] it should be under these folders: src/eBot/Match/Match.php
