### ISSUE TITLE
Problem with bootstrap.php

### ISSUE THREAD

**Issue by stranden** [deStrO/eBot-CSGO#82]
Hello,

I'm new here in the eBot world, but the project is looking good. 
So i wanted to give it a chance.

Sadly I have faced some errors in the process of installing the eBot system.

I have compiled PHP version 7.0.5 but mysql wasn't enabled so I did a recompile with mysqli instead.

So I have changed bootstrap.php to check for MySQLi instead of MySQL, chould this course some errors?

bootstrap.php look like this, then I try to start the bot.

![image](https://cloud.githubusercontent.com/assets/18518722/14835600/cf14c620-0c0a-11e6-8598-e20e5aafd0cd.png)

**Comment by Existeeence** [comment]
Use PHP 5.5.15.
You'll need to manually compile it unless you can find a prebuiilt. 

Or, you can use @burnedram's patch: https://github.com/burnedram/eBoot-CSGO

**Comment by stranden** [comment]
Thanks!
I used a combination of @burnedram's patch but changed the PHP version to PHP 5.5.15.

So now is the bot online!

![image](https://cloud.githubusercontent.com/assets/18518722/14865192/ce581fa8-0cbd-11e6-8c46-2a072bf44305.png)
