### ISSUE TITLE
Integration  eBot-CSGO with Drupal 7

### ISSUE THREAD

**Issue by lexasorokin** [deStrO/eBot-CSGO#83]
Hey, somebody engaged in system eBot-CSGO integration with Drupal? Maybe have tutorial. Or anyone can help?

**Comment by mgjuhler** [comment]
Why would you need to integrate ebot with drupal? I am just curious 😊

**Comment by lexasorokin** [comment]
The customer wants on the site (made on Drupal), appeared statistics from eBot, users / ID's  have been synchronized and etc..

**Comment by lexasorokin** [comment]
The customer wants on the site (made on Drupal), appeared statistics from eBot, users / ID's have been synchronized and etc..
