### ISSUE TITLE
Map does not change at match start

### ISSUE THREAD

**Issue by digitalfarseer** [deStrO/eBot-CSGO#86]
Map does not change after match start. I have "Changing map to _my_map_" in log, but have no effect onto my server.

**Comment by MikkelDK** [comment]
Do you have started the eBot + RCON password is correctly?

**Comment by digitalfarseer** [comment]
Sure! Match work properly if i manually changing the map. I use master branch, without pthreads (pthreads crash cli.exe under win system).

**Comment by dayum87** [comment]
hey guys, i also have to change the map manually,

the output of the gameserver is
_20:33:26 Rcon: "changelevel workshop/125439125/de_nuke"_
but there is no mapchange after this.

Did u find a solution?

**Comment by MikkelDK** [comment]
Maybe you need to try update /reinstall to the new eBot version.
