### ISSUE TITLE
GOTV Crashing Post Game

### ISSUE THREAD

**Issue by IzanCSGM** [deStrO/eBot-CSGO#88]
With tv_delaymapchange 1 in a cfg file I have loaded when starting an eBot public match once a team wins the game (i.e 16-10) we lose GOTV connection and lose 120 seconds of game play.

How to I fix this?

**Comment by KoSoVaR** [comment]
This is norma behavior because of the delay. Don't shut down the game
server until after the delay is over (I.e 180 seconds after the match ends)

**Comment by IzanCSGM** [comment]
I am not shutting anything down.  The game ends and eBot runs some sort of cfg and the GOTV ends.

**Comment by KoSoVaR** [comment]
If the server shuts down before the delay is over then you will not see the
end of the match. I learned this the hard way at a recent tournament.  Are
you manually stopping the server after eBot match is complete?  Perhaps
someone can chime in on how the match and GOTV are handled after match
end.  But strip eBot away and the game server must stay up at least as long
as the GOTV delay is.

**Comment by IzanCSGM** [comment]
No man we are not shutting it down.  As soon as the match is over the scoreboard shows for like 3 seconds and ebot kills the GOTV.  The server stays on the map, does not reset, does not shut down.

**Comment by KoSoVaR** [comment]
Understood, that's why I did say I think we need to look at the logic of
how match end and GOTV are handled.  It's a little late here and I'm
probably not the best person to help. I think @heew has been super active
recently and may be able to chime in.

**Comment by Versatile-BFG** [comment]
It does a stop record and executes the server config. Check your server config for anything that may stuff it up. This is from the base branch from deStrO. Not sure what branch you are using.

**Comment by IzanCSGM** [comment]
CL_FlushEntityPacket, Update delta not found

This is the message my casters get on GOTV after the game ends in real time (GOTV is 120 seconds behind real time)

**Comment by mgjuhler** [comment]
http://forums.steampowered.com/forums/showthread.php?t=1379315

Mads Juhler
Langstrengvej 13
6100 Haderslev
Tlf: 2942 0778

2016-05-14 21:53 GMT+02:00 IzanCSGM <notifications@github.com>:

**Comment by IzanCSGM** [comment]
This is a GOTV issue not a demo problem.  eBot is running a command at the end of the match killing the GOTV connection.

**Comment by Gicminos** [comment]
Same problem

**Comment by deStrO** [comment]
There is an issue with the demo upload function, I'll update the plugin tomorrow.

**Comment by AlthalusAvan** [comment]
Do we have an update on this? Are people still having this issue? I had it at a tournament several months ago but assumed it was a configuration error on my end,
