### ISSUE TITLE
bug lunch bootstrap

### ISSUE THREAD

**Issue by pymouse** [deStrO/eBot-CSGO#90]
hi guys i'm soucis lunch bootsrap.php

![notwork](https://cloud.githubusercontent.com/assets/19509207/15450574/20fa1042-1f9f-11e6-859b-1ab1f85ccd66.JPG)
thanks for solutions :)

**Comment by deStrO** [comment]
Please follow this guide: http://forum.esport-tools.net/d/2-how-to-install-ebot-on-debian-ubuntu-for-beginners/86
