### ISSUE TITLE
TACTICAL PAUSE

### ISSUE THREAD

**Issue by hpksoldati** [deStrO/eBot-CSGO#92]
How do i set in 'match.php' tactical pause for 2 minutes? (LIKE IN MLG I THINK)

**Comment by niltonraj** [comment]
Hello, I have this same doubt. Did you figure out how to set aside time for the pause?

**Comment by Mariapori** [comment]
I made new task and command for Match.php

Command !tac pause game normally but execute task with delay to automatically unpause. 

I send code snippet if i get it work perfectly.
