### ISSUE TITLE
eBot bugged

### ISSUE THREAD

**Issue by MikkelDK** [deStrO/eBot-CSGO#97]
Hello,

the status with:
Websocket online
eBot online
Sound ON:

It' just bugged. some minutes it show "Loading...." where the bootstrap.php is running behind screen.

What can i do?

![](https://i.gyazo.com/342758e802d7324111a93d43f479e8e3.png)

After it just show:
Loading...
Loading...

(Where the other buttons dont works - without i need to restart the bootstrap each 5 minutes 24/7!)

**Comment by deStrO** [comment]
Sometimes the websocket is crashing inside the php daemon and it's not auto restarted.
What I do in my case: I comment the nodejs start code and I launch it with "forever" (npm install -g forever)

**Comment by MikkelDK** [comment]
So you will recommend i need to use "forever" ? :)

**Comment by deStrO** [comment]
Yep :)

**Comment by MikkelDK** [comment]
I will do it, for next tournament i hosting! ;) - it's very good!
i waiting for you reply on private email! :) 

- Good product you has created!!

**Comment by MikkelDK** [comment]
I forget to ask:

just this?
forever start bootstrap.php ?

**Comment by deStrO** [comment]
forever start websocket_server.js ip port

**Comment by MikkelDK** [comment]
@deStrO - i did the command with forever start.

Websocket Online.
How to start eBot up?
if i try: php bootstrap.php > error: Websocket Server crashed.

What can i do?

**Comment by deStrO** [comment]
As I said, you need to comment in bootstrap.php that part. From line 83 to line 112, you can comment them all.

**Comment by MikkelDK** [comment]
aka remove the code? or just set // ?

**Comment by MikkelDK** [comment]
i did restart the forever start of websocket_server.js - it works now! - THANKS for your help!

**Comment by MikkelDK** [comment]
New error under websocket_server.js

SyntaxError: Unexpected token �
    at Object.parse (native)
    at Socket.<anonymous> (/home/ebot/ebot-csgo/websocket_server.js:166:30)
    at emitTwo (events.js:100:13)
    at Socket.emit (events.js:185:7)
    at UDP.onMessage (dgram.js:529:8)

**Comment by deStrO** [comment]
Be carreful, you need to launch the websocket on the exact same IP + PORT

**Comment by MikkelDK** [comment]
I did what you said: the websocket work. and i did remove the "websocket code" under bootstrap.php

And it´s loaded (behind screen)
But on the site it´s just "Loading" on eBot.
Do you want SSH access?

**Comment by MikkelDK** [comment]
From line 83 to line 112 of bootstrap.php

`echo "| Registerung Shutdown function !" . PHP_EOL;
register_shutdown_function('handleShutdown');


// Starting ebot Websocket Server
if (PHP_OS == "Linux") {
    echo "| Starting eBot Websocket-Server !" . PHP_EOL;
    $descriptorspec = array(
        0 => array("pipe", "r"),
        1 => array("file", APP_ROOT . "logs" . DIRECTORY_SEPARATOR . "websocket.log", "a"),
//        1 => array("pipe", "w"),
        2 => array("file", APP_ROOT . "logs" . DIRECTORY_SEPARATOR . "websocket.error", "a")
//        2 => array("pipe", "w")
    );
    $webSocketProcess = proc_open('node ' . APP_ROOT . 'websocket_server.js ' . \eBot\Config\Config::getInstance()->getBot_ip() . ' ' . \eBot\Config\Config::getInstance()->getBot_$
    if (is_resource($webSocketProcess)) {
        fclose($pipes[0]);
        usleep(400000);
        $status = proc_get_status($webSocketProcess);
        if (!$status['running']) {
            echo '| WebSocket server crashed' . PHP_EOL;
            echo '-----------------------------------------------------' . PHP_EOL;
            die();
        }
        echo "| WebSocket has been started" . PHP_EOL;
    }
} else {
    echo "| You are under windows, please run websocket_server.bat before starting ebot" . PHP_EOL;
    sleep(5);
}
`
What can i do there?

**Comment by MikkelDK** [comment]
Fatal error: Class 'eBot\Manager\ReportManager' not found in /home/ebot/ebot-csgo/src/eBot/Application/Application.php on line 55
Segmentation fault

**Comment by MikkelDK** [comment]
Did i do something wrong. - since it's just need to be ready from thursday.
@heew - maybe you can see here, and maybe give tip. - it's just the bootstrap.php (since i want the websocket removed) but websocket running "alone perfect" but eBot never coming up.

**Comment by MikkelDK** [comment]
Got anything fixed, i did remove some wrong codes! ;)

**Comment by b0rZ84** [comment]
Hi,

I have the same problem (ebot status stuck: Loading), websocket running, bootstrap.php running. Tried running forever but didn't work out.

~/ebot$ forever start websocket_server.js 79.172.xxx.xxx 12361
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: websocket_server.js

websocket.log:

info: socket.io started
Thu Jul 20 2017 15:07:03 GMT+0200 (CEST) Server is listening on port 12360
UDP Server listening on 79.172.193.169:12361

Any idea why this happen? :)

**Comment by b0rZ84** [comment]
Okay, restarting the server solved this. Funny. :)
