### ISSUE TITLE
send of 24 bytes failed with errno=32 

### ISSUE THREAD

**Issue by MikkelDK** [deStrO/eBot-CSGO#99]
Hello,

I did try to edit on Match.php for show damage over 100.

$message->attackerDamage = $this->roundData[$this->getNbRound()][$message->victimTeam]["HEALTH_LEFT"][$message->victimName];

But i got this error for starting:
Notice: fwrite(): send of 24 bytes failed with errno=32 Broken pipe in /home/ebot/ebot-csgo/websocket/websocket.functions.php on line 59^

**Comment by MikkelDK** [comment]
@deStrO @heew - Do you has see this error before?

**Comment by deStrO** [comment]
This look like the websocket_server crashed, it's related to your old ticket.

**Comment by heew** [comment]
@MikkelDK no I haven't seen this before.
